language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS autosleep;" -uroot
script:
  - ./gradlew check -Dintegration-test=true
branches:
  only:
    - master
    - develop
    - /^feature-.*$/
    - /^fix-.*$/
after_success:
  - ./gradlew jacocoTestReport coveralls 
